#%RAML 1.0 DataType
displayName: ping datatype
description: Heartbeat API response
type: object
properties:
  status:
    required: true
    description: status code
    type: string
  message:
    required: true
    description: status message
    type: string