#%RAML 1.0 Trait
headers:
  Accept: 
    description: HTTP-Standard Parameter. Header Field RFC 7231. Media Types RFC 2046.
    type: string
    required: true
    default: application/json
    example: 'Accept: application/json'
      