#%RAML 1.0 Trait
responses:
  200:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'

  201:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'

  204:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'

  400:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'

  401:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'

  403:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'

  404:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'

  405:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'

  406:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'

  415:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'

  500:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'

  501:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'

  502:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'

  503:
    headers:
      Access-Control-Allow-Origin: 
        example:
          '*'
      Access-Control-Allow-Methods: 
        example:
          '*'